name: Build and Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install SSH Client (pull request previews)
      continue-on-error: true
      if: github.event_name == 'pull_request'
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.FRANKLIN_PRIV_PREVIEW }}

    - name: Install SSH Client (main)
      if: github.ref == 'refs/heads/dev' && (github.event_name == 'push' || github.event_name == 'schedule')
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.FRANKLIN_PRIV }}

    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install matplotlib
      run: pip install matplotlib

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.4.1

    - name: Build site with Franklin.jl
      run: julia -e '
            using Pkg; Pkg.add(["NodeJS", "Franklin"]);
            using NodeJS; run(`$(npm_cmd()) install highlight.js`);
            using Franklin;
            Pkg.activate("."); Pkg.instantiate();
            optimize()'
    
    - run: echo "You can preview this pull request at https://juliahealth.org/juliahealth.github.io-previews/previews/PR${{ github.event.number }}"
      if: github.event_name == 'pull_request'

    - name: Deploy (pull request previews)
      continue-on-error: true
      if: github.event_name == 'pull_request'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: __site
        REPOSITORY_NAME: JuliaHealth/juliahealth.github.io-previews
        SSH: true
        TARGET_FOLDER: "previews/PR${{ github.event.number }}"

    - name: Deploy (main)
      if: github.ref == 'refs/heads/dev' && (github.event_name == 'push' || github.event_name == 'schedule')
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: master
        FOLDER: __site
        SSH: true
